# Site wide configuration

title:            J.D. Flynn and the Adventures in Web Development
locale:           en_US
url:              https://www.jamesdflynn.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
#  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: J.D. Flynn
  avatar: profile.jpg
  bio: "Web developer by trade, geek by choice, getting stuff done in the Chicagoland area."
  email: jd@jamesdflynn.com
  disqus-shortname: jamesdflynn
  twitter: JDDoesDev
  facebook: #username
  google:
    plus: #username
    analytics: UA-60490227-1
    verify: byemwVOh8JIg3XatAJz2TwH16xSHbOLLKl47oQTTLZE
    ad-client: ca-pub-9258516687573779
    ad-slot: 7134545736
  bing-verify:
  github: JDDoesDev
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: jflynn8
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  paypal: JDDoesDev

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
gems: ['jekyll-twitter-plugin']

twitter:
  consumer_key: q97Y4aJw4o3rCTojW4jyorI4M
  consumer_secret: xrAQTMz7laWx0p1RCQQaSMpQFeRMsyQygMhTfSdCkmpS0Zxqpt
  access_token: 25409555-GqjDmzZ7SXYy8WqZHODdbZ4r2vCjOKy1kOStqbS2P
  access_token_secret: lyT8EAACITjBN9YCe0vVTCsWHaHabNI7rZePwaZW81KFE
